import { computed, toValue } from "vue";
import { useId } from "@vue-aria/ssr";
import type { Key, MaybeReactive, ReadonlyRef } from "@vue-aria/types";
import { useDisclosure } from "./useDisclosure";
import { useDisclosureState } from "./useDisclosureState";
import type { UseDisclosureResult } from "./useDisclosure";
import type { UseDisclosureGroupStateResult } from "./useDisclosureGroupState";

export interface UseAccordionItemOptions {
  id?: MaybeReactive<Key | undefined>;
  isDisabled?: MaybeReactive<boolean | undefined>;
  onExpandedChange?: (isExpanded: boolean) => void;
}

export interface UseAccordionItemResult extends UseDisclosureResult {
  id: ReadonlyRef<Key>;
  isExpanded: ReadonlyRef<boolean>;
  isDisabled: ReadonlyRef<boolean>;
}

function resolveBoolean(value: MaybeReactive<boolean | undefined> | undefined): boolean {
  if (value === undefined) {
    return false;
  }

  return Boolean(toValue(value));
}

function isSameSet(left: Set<Key>, right: Set<Key>): boolean {
  if (left.size !== right.size) {
    return false;
  }

  for (const key of left) {
    if (!right.has(key)) {
      return false;
    }
  }

  return true;
}

function updateExpandedKey(
  state: UseDisclosureGroupStateResult,
  key: Key,
  isExpanded: boolean
): void {
  const nextKeys = new Set(state.expandedKeys.value);
  if (isExpanded) {
    if (!state.allowsMultipleExpanded.value) {
      nextKeys.clear();
    }
    nextKeys.add(key);
  } else {
    nextKeys.delete(key);
  }

  if (isSameSet(nextKeys, state.expandedKeys.value)) {
    return;
  }

  state.setExpandedKeys(nextKeys);
}

export function useAccordionItem(
  options: UseAccordionItemOptions,
  groupState: UseDisclosureGroupStateResult,
  panelRef: MaybeReactive<HTMLElement | null | undefined>
): UseAccordionItemResult {
  const autogeneratedId = useId(undefined, "v-aria-accordion-item");
  const id = computed<Key>(() => {
    if (options.id === undefined) {
      return autogeneratedId.value;
    }

    return toValue(options.id) ?? autogeneratedId.value;
  });

  const isExpanded = computed(() =>
    groupState.expandedKeys.value.has(id.value)
  );
  const isDisabled = computed(
    () => resolveBoolean(options.isDisabled) || groupState.isDisabled.value
  );

  const state = useDisclosureState({
    isExpanded,
    onExpandedChange: (nextExpanded) => {
      updateExpandedKey(groupState, id.value, nextExpanded);
      options.onExpandedChange?.(nextExpanded);
    },
  });

  const disclosure = useDisclosure(
    {
      isExpanded,
      isDisabled,
      onExpandedChange: options.onExpandedChange,
    },
    state,
    panelRef
  );

  return {
    ...disclosure,
    id,
    isExpanded,
    isDisabled,
  };
}
