import { defineConfig } from "vitepress";

export default defineConfig({
  title: "Vue Aria",
  description: "Vue 3 parity port of React Aria and React Spectrum",
  themeConfig: {
    nav: [
      { text: "Guide", link: "/" },
      { text: "Utils", link: "/packages/utils" },
      { text: "Collections", link: "/packages/collections" },
      { text: "Utils State", link: "/packages/utils-state" },
      { text: "Toggle State", link: "/packages/toggle-state" },
      { text: "Tabs State", link: "/packages/tabs-state" },
      { text: "Grid State", link: "/packages/grid-state" },
      { text: "Table State", link: "/packages/table-state" },
      { text: "Tree State", link: "/packages/tree-state" },
      { text: "Calendar State", link: "/packages/calendar-state" },
      { text: "DatePicker State", link: "/packages/datepicker-state" },
      { text: "Toast State", link: "/packages/toast-state" },
      { text: "Tabs", link: "/packages/tabs" },
      { text: "Grid", link: "/packages/grid" },
      { text: "GridList", link: "/packages/gridlist" },
      { text: "Table", link: "/packages/table" },
      { text: "Tree", link: "/packages/tree" },
      { text: "Calendar", link: "/packages/calendar" },
      { text: "DatePicker", link: "/packages/datepicker" },
      { text: "Selection", link: "/packages/selection" },
      { text: "Selection State", link: "/packages/selection-state" },
      { text: "I18n", link: "/packages/i18n" },
      { text: "Interactions", link: "/packages/interactions" },
      { text: "Focus", link: "/packages/focus" },
      { text: "SSR", link: "/packages/ssr" },
      { text: "Live Announcer", link: "/packages/live-announcer" },
      { text: "Aria Modal Polyfill", link: "/packages/aria-modal-polyfill" },
      { text: "Landmark", link: "/packages/landmark" },
      { text: "Toast", link: "/packages/toast" },
      { text: "Visually Hidden", link: "/packages/visually-hidden" },
      { text: "Label", link: "/packages/label" },
      { text: "Button", link: "/packages/button" },
      { text: "ActionGroup", link: "/packages/actiongroup" },
      { text: "Link", link: "/packages/link" },
      { text: "Toggle", link: "/packages/toggle" },
      { text: "Checkbox", link: "/packages/checkbox" },
      { text: "Radio", link: "/packages/radio" },
      { text: "Switch", link: "/packages/switch" },
      { text: "TextField", link: "/packages/textfield" },
      { text: "SearchField", link: "/packages/searchfield" },
      { text: "Form", link: "/packages/form" },
      { text: "Form State", link: "/packages/form-state" },
      { text: "SpinButton", link: "/packages/spinbutton" },
      { text: "NumberField", link: "/packages/numberfield" },
      { text: "Slider", link: "/packages/slider" },
      { text: "Spectrum Slider", link: "/packages/spectrum-slider" },
      { text: "Spectrum Button", link: "/packages/spectrum-button" },
      { text: "Spectrum Checkbox", link: "/packages/spectrum-checkbox" },
      { text: "Spectrum CheckboxGroup", link: "/packages/spectrum-checkbox-group" },
      { text: "Spectrum Radio", link: "/packages/spectrum-radio" },
      { text: "Spectrum Switch", link: "/packages/spectrum-switch" },
      { text: "Spectrum Link", link: "/packages/spectrum-link" },
      { text: "Spectrum TextField", link: "/packages/spectrum-textfield" },
      { text: "Spectrum TextArea", link: "/packages/spectrum-textarea" },
      { text: "Spectrum SearchField", link: "/packages/spectrum-searchfield" },
      { text: "Spectrum NumberField", link: "/packages/spectrum-numberfield" },
      { text: "Spectrum Breadcrumbs", link: "/packages/spectrum-breadcrumbs" },
      { text: "Spectrum Dialog", link: "/packages/spectrum-dialog" },
      { text: "Spectrum Tooltip", link: "/packages/spectrum-tooltip" },
      { text: "Spectrum Toast", link: "/packages/spectrum-toast" },
      { text: "Spectrum Menu", link: "/packages/spectrum-menu" },
      { text: "Spectrum ProgressBar", link: "/packages/spectrum-progressbar" },
      { text: "Spectrum ProgressCircle", link: "/packages/spectrum-progresscircle" },
      { text: "Spectrum Meter", link: "/packages/spectrum-meter" },
      { text: "Spectrum ActionButton", link: "/packages/spectrum-action-button" },
      { text: "Spectrum LogicButton", link: "/packages/spectrum-logic-button" },
      { text: "Spectrum ToggleButton", link: "/packages/spectrum-toggle-button" },
      { text: "Spectrum Theme", link: "/packages/spectrum-theme" },
      { text: "Spectrum Theme Express", link: "/packages/spectrum-theme-express" },
      { text: "Spectrum Theme Light", link: "/packages/spectrum-theme-light" },
      { text: "Spectrum Theme Dark", link: "/packages/spectrum-theme-dark" },
      { text: "Spectrum Provider", link: "/packages/provider" },
      { text: "Spectrum Utils", link: "/packages/spectrum-utils" },
      { text: "Slider State", link: "/packages/slider-state" },
      { text: "NumberField State", link: "/packages/numberfield-state" },
      { text: "Progress", link: "/packages/progress" },
      { text: "Meter", link: "/packages/meter" },
      { text: "Dialog", link: "/packages/dialog" },
      { text: "Breadcrumbs", link: "/packages/breadcrumbs" },
      { text: "Separator", link: "/packages/separator" },
      { text: "Tooltip", link: "/packages/tooltip" },
      { text: "Disclosure", link: "/packages/disclosure" },
      { text: "Overlays", link: "/packages/overlays" },
      { text: "ListBox", link: "/packages/listbox" },
      { text: "List State", link: "/packages/list-state" },
      { text: "Select", link: "/packages/select" },
      { text: "Menu", link: "/packages/menu" },
      { text: "ComboBox State", link: "/packages/combobox-state" },
      { text: "ComboBox", link: "/packages/combobox" },
    ],
    sidebar: [
      {
        text: "Packages",
        items: [
          { text: "@vue-aria/utils", link: "/packages/utils" },
          { text: "@vue-aria/collections", link: "/packages/collections" },
          { text: "@vue-aria/utils-state", link: "/packages/utils-state" },
          { text: "@vue-aria/toggle-state", link: "/packages/toggle-state" },
          { text: "@vue-aria/tabs-state", link: "/packages/tabs-state" },
          { text: "@vue-aria/grid-state", link: "/packages/grid-state" },
          { text: "@vue-aria/table-state", link: "/packages/table-state" },
          { text: "@vue-aria/tree-state", link: "/packages/tree-state" },
          { text: "@vue-aria/calendar-state", link: "/packages/calendar-state" },
          { text: "@vue-aria/datepicker-state", link: "/packages/datepicker-state" },
          { text: "@vue-aria/toast-state", link: "/packages/toast-state" },
          { text: "@vue-aria/tabs", link: "/packages/tabs" },
          { text: "@vue-aria/grid", link: "/packages/grid" },
          { text: "@vue-aria/gridlist", link: "/packages/gridlist" },
          { text: "@vue-aria/table", link: "/packages/table" },
          { text: "@vue-aria/tree", link: "/packages/tree" },
          { text: "@vue-aria/calendar", link: "/packages/calendar" },
          { text: "@vue-aria/datepicker", link: "/packages/datepicker" },
          { text: "@vue-aria/selection", link: "/packages/selection" },
          { text: "@vue-aria/selection-state", link: "/packages/selection-state" },
          { text: "@vue-aria/i18n", link: "/packages/i18n" },
          { text: "@vue-aria/interactions", link: "/packages/interactions" },
          { text: "@vue-aria/focus", link: "/packages/focus" },
          { text: "@vue-aria/ssr", link: "/packages/ssr" },
          { text: "@vue-aria/live-announcer", link: "/packages/live-announcer" },
          { text: "@vue-aria/aria-modal-polyfill", link: "/packages/aria-modal-polyfill" },
          { text: "@vue-aria/landmark", link: "/packages/landmark" },
          { text: "@vue-aria/toast", link: "/packages/toast" },
          { text: "@vue-aria/visually-hidden", link: "/packages/visually-hidden" },
          { text: "@vue-aria/label", link: "/packages/label" },
          { text: "@vue-aria/button", link: "/packages/button" },
          { text: "@vue-aria/actiongroup", link: "/packages/actiongroup" },
          { text: "@vue-aria/link", link: "/packages/link" },
          { text: "@vue-aria/toggle", link: "/packages/toggle" },
          { text: "@vue-aria/checkbox", link: "/packages/checkbox" },
          { text: "@vue-aria/radio", link: "/packages/radio" },
          { text: "@vue-aria/switch", link: "/packages/switch" },
          { text: "@vue-aria/textfield", link: "/packages/textfield" },
          { text: "@vue-aria/searchfield", link: "/packages/searchfield" },
          { text: "@vue-aria/form", link: "/packages/form" },
          { text: "@vue-aria/form-state", link: "/packages/form-state" },
          { text: "@vue-aria/spinbutton", link: "/packages/spinbutton" },
          { text: "@vue-aria/numberfield", link: "/packages/numberfield" },
          { text: "@vue-aria/slider", link: "/packages/slider" },
          { text: "@vue-spectrum/slider", link: "/packages/spectrum-slider" },
          { text: "@vue-spectrum/button", link: "/packages/spectrum-button" },
          { text: "@vue-spectrum/checkbox", link: "/packages/spectrum-checkbox" },
          { text: "@vue-spectrum/checkbox CheckboxGroup", link: "/packages/spectrum-checkbox-group" },
          { text: "@vue-spectrum/radio", link: "/packages/spectrum-radio" },
          { text: "@vue-spectrum/switch", link: "/packages/spectrum-switch" },
          { text: "@vue-spectrum/link", link: "/packages/spectrum-link" },
          { text: "@vue-spectrum/textfield TextField", link: "/packages/spectrum-textfield" },
          { text: "@vue-spectrum/textfield TextArea", link: "/packages/spectrum-textarea" },
          { text: "@vue-spectrum/searchfield", link: "/packages/spectrum-searchfield" },
          { text: "@vue-spectrum/numberfield", link: "/packages/spectrum-numberfield" },
          { text: "@vue-spectrum/breadcrumbs", link: "/packages/spectrum-breadcrumbs" },
          { text: "@vue-spectrum/dialog", link: "/packages/spectrum-dialog" },
          { text: "@vue-spectrum/tooltip", link: "/packages/spectrum-tooltip" },
          { text: "@vue-spectrum/toast", link: "/packages/spectrum-toast" },
          { text: "@vue-spectrum/menu", link: "/packages/spectrum-menu" },
          { text: "@vue-spectrum/progress ProgressBar", link: "/packages/spectrum-progressbar" },
          { text: "@vue-spectrum/progress ProgressCircle", link: "/packages/spectrum-progresscircle" },
          { text: "@vue-spectrum/meter", link: "/packages/spectrum-meter" },
          { text: "@vue-spectrum/button ActionButton", link: "/packages/spectrum-action-button" },
          { text: "@vue-spectrum/button LogicButton", link: "/packages/spectrum-logic-button" },
          { text: "@vue-spectrum/button ToggleButton", link: "/packages/spectrum-toggle-button" },
          { text: "@vue-spectrum/theme", link: "/packages/spectrum-theme" },
          { text: "@vue-spectrum/theme-express", link: "/packages/spectrum-theme-express" },
          { text: "@vue-spectrum/theme-light", link: "/packages/spectrum-theme-light" },
          { text: "@vue-spectrum/theme-dark", link: "/packages/spectrum-theme-dark" },
          { text: "@vue-spectrum/provider", link: "/packages/provider" },
          { text: "@vue-spectrum/utils", link: "/packages/spectrum-utils" },
          { text: "@vue-aria/slider-state", link: "/packages/slider-state" },
          { text: "@vue-aria/numberfield-state", link: "/packages/numberfield-state" },
          { text: "@vue-aria/progress", link: "/packages/progress" },
          { text: "@vue-aria/meter", link: "/packages/meter" },
          { text: "@vue-aria/dialog", link: "/packages/dialog" },
          { text: "@vue-aria/breadcrumbs", link: "/packages/breadcrumbs" },
          { text: "@vue-aria/separator", link: "/packages/separator" },
          { text: "@vue-aria/tooltip", link: "/packages/tooltip" },
          { text: "@vue-aria/disclosure", link: "/packages/disclosure" },
          { text: "@vue-aria/overlays", link: "/packages/overlays" },
          { text: "@vue-aria/listbox", link: "/packages/listbox" },
          { text: "@vue-aria/list-state", link: "/packages/list-state" },
          { text: "@vue-aria/select", link: "/packages/select" },
          { text: "@vue-aria/menu", link: "/packages/menu" },
          { text: "@vue-aria/combobox-state", link: "/packages/combobox-state" },
          { text: "@vue-aria/combobox", link: "/packages/combobox" },
        ],
      },
    ],
  },
});
