import { defineConfig } from "vitepress";

export default defineConfig({
  title: "Vue Aria",
  description: "Vue 3 parity port of React Aria and React Spectrum",
  themeConfig: {
    nav: [
      { text: "Guide", link: "/" },
      { text: "Selection", link: "/packages/selection" },
      { text: "Selection State", link: "/packages/selection-state" },
      { text: "I18n", link: "/packages/i18n" },
      { text: "Interactions", link: "/packages/interactions" },
      { text: "Focus", link: "/packages/focus" },
      { text: "SSR", link: "/packages/ssr" },
      { text: "Live Announcer", link: "/packages/live-announcer" },
      { text: "Aria Modal Polyfill", link: "/packages/aria-modal-polyfill" },
      { text: "Landmark", link: "/packages/landmark" },
      { text: "Toast", link: "/packages/toast" },
      { text: "Visually Hidden", link: "/packages/visually-hidden" },
      { text: "Label", link: "/packages/label" },
      { text: "Button", link: "/packages/button" },
      { text: "ActionGroup", link: "/packages/actiongroup" },
      { text: "Link", link: "/packages/link" },
      { text: "Toggle", link: "/packages/toggle" },
      { text: "Checkbox", link: "/packages/checkbox" },
      { text: "Radio", link: "/packages/radio" },
      { text: "Switch", link: "/packages/switch" },
      { text: "TextField", link: "/packages/textfield" },
      { text: "SearchField", link: "/packages/searchfield" },
      { text: "Form", link: "/packages/form" },
      { text: "Form State", link: "/packages/form-state" },
      { text: "SpinButton", link: "/packages/spinbutton" },
      { text: "NumberField", link: "/packages/numberfield" },
      { text: "Slider", link: "/packages/slider" },
      { text: "NumberField State", link: "/packages/numberfield-state" },
      { text: "Progress", link: "/packages/progress" },
      { text: "Meter", link: "/packages/meter" },
      { text: "Dialog", link: "/packages/dialog" },
      { text: "Breadcrumbs", link: "/packages/breadcrumbs" },
      { text: "Separator", link: "/packages/separator" },
      { text: "Tooltip", link: "/packages/tooltip" },
      { text: "Disclosure", link: "/packages/disclosure" },
      { text: "Overlays", link: "/packages/overlays" },
      { text: "ListBox", link: "/packages/listbox" },
      { text: "List State", link: "/packages/list-state" },
      { text: "Select", link: "/packages/select" },
      { text: "Menu", link: "/packages/menu" },
    ],
    sidebar: [
      {
        text: "Packages",
        items: [
          { text: "@vue-aria/selection", link: "/packages/selection" },
          { text: "@vue-aria/selection-state", link: "/packages/selection-state" },
          { text: "@vue-aria/i18n", link: "/packages/i18n" },
          { text: "@vue-aria/interactions", link: "/packages/interactions" },
          { text: "@vue-aria/focus", link: "/packages/focus" },
          { text: "@vue-aria/ssr", link: "/packages/ssr" },
          { text: "@vue-aria/live-announcer", link: "/packages/live-announcer" },
          { text: "@vue-aria/aria-modal-polyfill", link: "/packages/aria-modal-polyfill" },
          { text: "@vue-aria/landmark", link: "/packages/landmark" },
          { text: "@vue-aria/toast", link: "/packages/toast" },
          { text: "@vue-aria/visually-hidden", link: "/packages/visually-hidden" },
          { text: "@vue-aria/label", link: "/packages/label" },
          { text: "@vue-aria/button", link: "/packages/button" },
          { text: "@vue-aria/actiongroup", link: "/packages/actiongroup" },
          { text: "@vue-aria/link", link: "/packages/link" },
          { text: "@vue-aria/toggle", link: "/packages/toggle" },
          { text: "@vue-aria/checkbox", link: "/packages/checkbox" },
          { text: "@vue-aria/radio", link: "/packages/radio" },
          { text: "@vue-aria/switch", link: "/packages/switch" },
          { text: "@vue-aria/textfield", link: "/packages/textfield" },
          { text: "@vue-aria/searchfield", link: "/packages/searchfield" },
          { text: "@vue-aria/form", link: "/packages/form" },
          { text: "@vue-aria/form-state", link: "/packages/form-state" },
          { text: "@vue-aria/spinbutton", link: "/packages/spinbutton" },
          { text: "@vue-aria/numberfield", link: "/packages/numberfield" },
          { text: "@vue-aria/slider", link: "/packages/slider" },
          { text: "@vue-aria/numberfield-state", link: "/packages/numberfield-state" },
          { text: "@vue-aria/progress", link: "/packages/progress" },
          { text: "@vue-aria/meter", link: "/packages/meter" },
          { text: "@vue-aria/dialog", link: "/packages/dialog" },
          { text: "@vue-aria/breadcrumbs", link: "/packages/breadcrumbs" },
          { text: "@vue-aria/separator", link: "/packages/separator" },
          { text: "@vue-aria/tooltip", link: "/packages/tooltip" },
          { text: "@vue-aria/disclosure", link: "/packages/disclosure" },
          { text: "@vue-aria/overlays", link: "/packages/overlays" },
          { text: "@vue-aria/listbox", link: "/packages/listbox" },
          { text: "@vue-aria/list-state", link: "/packages/list-state" },
          { text: "@vue-aria/select", link: "/packages/select" },
          { text: "@vue-aria/menu", link: "/packages/menu" },
        ],
      },
    ],
  },
});
